apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "jx.fullname" . }}
rules:
  - apiGroups:
      - jenkins.io
    resources:
      - pipelineactivities
    verbs:
      - list
      - get
      - watch
