apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "jx.fullname" . }}
  labels:
    app: {{ template "jx.fullname" . }}
    chart: {{ template "jx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "jx.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "jx.fullname" . }}
        release: {{ .Release.Name }}
  {{- if .Values.podAnnotations }}
      annotations:
      {{ toYaml .Values.podAnnotations | indent 8 }}
  {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceaccount.customName }}
      serviceAccountName: {{ template "jx.fullname" . }}
      containers:
          - name: {{ .Chart.Name }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            ports:
              - name: http
                containerPort: {{ .Values.internalPort }}
                protocol: TCP
            livenessProbe:
              httpGet:
                path: /healthz
                port: http
            readinessProbe:
              httpGet:
                path: /readyz
                port: http
  {{- if .Values.env }}
            env:
              - name: JX_DB_INSTANCE_CONNECTION_NAME
                valueFrom:
                  secretKeyRef:
                    key: dbInstanceConnectionName
                    name: {{ template "jx.fullname" . }}
              - name: JX_DB_DATABASE_NAME
                valueFrom:
                  secretKeyRef:
                    key: dbDatabaseName
                    name: {{ template "jx.fullname" . }}
              - name: JX_DB_DATABASE_USER
                valueFrom:
                  secretKeyRef:
                    key: dbDatabaseUser
                    name: {{ template "jx.fullname" . }}
              - name: JX_DB_DATABASE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    key: dbDatabasePassword
                    name: {{ template "jx.fullname" . }}
  {{- range $pkey, $pval := .Values.env }}
              - name: {{ $pkey }}
                value: {{ $pval }}
                {{- end }}
                {{- end }}
            resources:
                {{ toYaml .Values.resources | indent 12 }}
                {{- with .Values.nodeSelector }}
      nodeSelector:
                {{ toYaml . | indent 8 }}
                {{- end }}
                {{- with .Values.affinity }}
      affinity:
                {{ toYaml . | indent 8 }}
                {{- end }}
                {{- with .Values.tolerations }}
      tolerations:
                {{ toYaml . | indent 8 }}
{{- end }}
